language: node_js
node_js:
- 12
script: 'true'
deploy:
#Branch - Development
- provider: elasticbeanstalk
#Access Key and Secret Key should be stored in travis-ci.com under the byjuweb org settings for each repo.
  access_key_id: "access key"
  secret_access_key: "secret id"
  region: ca-central-1
  app: sampletravis deployment
  env: Sampletravisdeployment-env
  bucket_name: digitalonus
  bucket_path: mocktest
  skip_cleanup: true
  on:
    branch: main
